module.exports = {
  siteURL: process.env.URL || 'http://localhost:8080',
  siteName: 'Virtual Sports',
  siteDescription: 'Science Communication blog and Research Network',
  siteImage: '/assets/images/default-image-virtual-sports.webp',
  lang: 'en',
  locale: 'en_uk',
  authorName: 'Thibault Fouquaert',
  authorURL: 'thibault-fouquaert',
  authorEmail: 'thibault.fouquaert@ugent.be',
  twitterSite: '@SportmanaUGent',
  twitterCreator: '@TFouquaert',
  address: {
    street: 'Watersportlaan 2',
    city: 'Ghent',
    zip: '9000',
    country: 'Belgium',
    phoneDisplay: '+32 4 71 38 13 31',
    phoneCall: '0032471381331',
    email: 'thibault.fouquaert@ugent.be',
  },
}
